# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      time: "12:00"
      day: "sunday"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    groups:
      dev-patch-minor-dependencies:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
