import oclif from 'eslint-config-oclif'

export default [
  ...oclif,
  {
    ignores: [
      '**/*.js',
      'dist/**/*',
      'coverage/**/*',
    ],
  },
  {
    files: ['**/*.ts'],
    languageOptions: {
      parserOptions: {
        ecmaFeatures: {
          modules: true,
        },
        ecmaVersion: 6,
        sourceType: 'module',
      },
    },
    rules: {
      '@stylistic/comma-dangle': 'warn',
      '@stylistic/comma-style': 'warn',
      '@stylistic/function-paren-newline': 'warn',
      '@stylistic/indent': 'warn',
      '@stylistic/indent-binary-ops': 'warn',
      '@stylistic/lines-between-class-members': 'warn',
      '@stylistic/object-curly-newline': 'warn',
      '@stylistic/operator-linebreak': 'warn',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-expressions': 'warn',
      'arrow-body-style': 'warn',
      camelcase: 'off',
      'getter-return': 'warn',
      'import/namespace': 'warn',
      'mocha/no-mocha-arrows': 'warn',
      'n/no-unsupported-features/node-builtins': 'warn',
      'n/shebang': 'warn',
      'no-await-in-loop': 'off',
      'no-undef': 'warn',
      'node/no-missing-import': 'off',
      'object-shorthand': 'warn',
      'perfectionist/sort-classes': 'warn',
      'perfectionist/sort-enums': 'warn',
      'perfectionist/sort-imports': 'warn',
      'perfectionist/sort-interfaces': 'warn',
      'perfectionist/sort-intersection-types': 'warn',
      'perfectionist/sort-named-imports': 'warn',
      'perfectionist/sort-object-types': 'warn',
      'perfectionist/sort-objects': 'warn',
      'perfectionist/sort-switch-case': 'warn',
      'perfectionist/sort-union-types': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-destructuring': 'warn',
      'prefer-object-spread': 'warn',
      'unicorn/filename-case': 'warn',
      'unicorn/no-anonymous-default-export': 'warn',
      'unicorn/no-array-for-each': 'off',
      'unicorn/no-useless-undefined': 'warn',
      'unicorn/numeric-separators-style': 'warn',
      'unicorn/prefer-array-find': 'warn',
      'unicorn/prefer-logical-operator-over-ternary': 'warn',
      'unicorn/prefer-node-protocol': 'warn',
      'unicorn/prefer-number-properties': 'warn',
      'unicorn/prefer-string-replace-all': 'warn',
      'unicorn/switch-case-braces': 'warn',
    },
  },
  {
    files: ['test/**/*.ts'],
    rules: {
      'prefer-arrow-callback': 'off',
    },
  },
]
